// Mọi chuỗi giao diện tiếng Việt tập trung ở đây — thêm ngôn ngữ khác sau
// mà không cần sửa component (v1: không dùng thư viện i18n).

export const s = {
  app: {
    name: 'Lapis',
    tagline: 'Một workspace cho mỗi khóa học',
  },
  nav: {
    settings: 'Cài đặt',
    close: 'Đóng',
  },
  dashboard: {
    eyebrow: 'Tổng quan học tập',
    titleA: 'Lịch học &',
    titleB: 'hạn chót',
    thisWeek: 'Tuần này',
    thisWeekEmpty: 'Chưa có lịch học cho tuần này — bấm "Nhập lịch từ LMS" bên dưới.',
    sessions: 'buổi',
    hours: 'giờ',
    upcoming: 'Sắp tới',
    upcomingEmpty: 'Chưa có hạn chót nào — nhiệm vụ sẽ xuất hiện ở đây.',
    overdue: 'quá hạn',
    courses: 'Khóa học',
    addCourse: 'Thêm khóa học',
    noCourses: 'Chưa có khóa học nào',
    noCoursesHint: 'Tạo khóa học đầu tiên để bắt đầu.',
    today: 'Hôm nay',
    todayEmpty: 'Không có buổi học nào hôm nay.',
    currentWeek: 'tuần này',
    tomorrow: 'Ngày mai',
    tomorrowEmpty: 'Không có buổi học nào ngày mai.',
    tasksCount: 'nhiệm vụ',
    sync: 'Nhập lịch từ LMS',
    syncing: 'Đang chờ extension…',
    syncFail: 'Extension chưa phản hồi — cài extension Lapis vào Chrome rồi thử lại.',
    syncEmpty: 'Extension phản hồi nhưng chưa có dữ liệu — hãy mở trang Lịch học trên LMS trước.',
    syncImported: 'buổi học đã nhập',
    syncNew: 'khóa học mới tạo',
    exportWeekIcs: 'Xuất .ics',
  },
  course: {
    back: 'Tổng quan',
    edit: 'Sửa khóa học',
    tasks: 'Nhiệm vụ',
    materials: 'Tài liệu',
    chat: 'Trò chuyện',
    chatHint: 'Trò chuyện với AI dựa trên tài liệu của khóa học — bước M3.',
    reconnectFolder: 'Cấp quyền lại',
    tasksTab: {
      add: 'Thêm nhiệm vụ',
      empty: 'Chưa có nhiệm vụ nào',
      emptyHint: 'Thêm nhiệm vụ thủ công, hoặc để AI tách từ PDF bài tập (M4).',
      open: 'Đang mở',
      done: 'Đã xong',
      editHint: 'Bấm vào tên để sửa',
    },
    materialsTab: {
      connect: 'Kết nối thư mục',
      connectHint:
        'Chọn thư mục tài liệu của khóa học trên máy bạn. File không rời khỏi máy — chỉ nội dung trích xuất được gửi cho AI (M3).',
      unsupported: 'Trình duyệt này chưa hỗ trợ File System Access API — hãy dùng Chrome hoặc Edge.',
      needPermission:
        'Trình duyệt đã hết hạn quyền truy cập thư mục (chuyện thường gặp sau khi khởi động lại).',
      grantAndScan: 'Cấp quyền & quét lại',
      connected: 'Đã kết nối',
      files: 'tệp',
      rescan: 'Quét lại',
      scanning: 'Đang quét…',
      changeFolder: 'Đổi thư mục',
      disconnect: 'Ngắt kết nối',
      emptyFolder: 'Thư mục trống hoặc toàn file bị ẩn',
      filterPlaceholder: 'Lọc tệp theo tên…',
      rootLabel: 'Gốc thư mục',
    },
    deleteDialog: {
      title: 'Xóa khóa học?',
      bodyPrefix: 'Xóa',
      bodySuffix:
        '? Toàn bộ nhiệm vụ, tài liệu và hội thoại của khóa học này sẽ bị xóa vĩnh viễn.',
      confirm: 'Xóa vĩnh viễn',
    },
  },
  courseDialog: {
    newTitle: 'Khóa học mới',
    editTitle: 'Sửa khóa học',
    nameLabel: 'Tên khóa học',
    namePlaceholder: 'VD: Kinh tế vi mô',
    lmsLabel: 'Tên trên LMS (không bắt buộc)',
    lmsPlaceholder: 'Khớp tên lớp trên LMS để đồng bộ lịch',
    colorLabel: 'Màu',
    errorName: 'Vui lòng nhập tên khóa học.',
  },
  taskDialog: {
    newTitle: 'Nhiệm vụ mới',
    editTitle: 'Sửa nhiệm vụ',
    titleLabel: 'Tên nhiệm vụ',
    titlePlaceholder: 'VD: Bài tập tuần 4',
    dueLabel: 'Hạn chót (không bắt buộc)',
    subtasksLabel: 'Việc con — mỗi dòng một việc',
    subtasksNew: 'Thêm việc con (mỗi dòng một việc — tùy chọn)',
    overdue: 'Quá hạn',
  },
  chat: {
    placeholder: 'Hỏi gì đó về tài liệu khóa học…',
    send: 'Gửi',
    stop: 'Dừng',
    filesInContext: 'tệp trong ngữ cảnh',
    noFolderHint: 'Chưa kết nối thư mục — chat vẫn hoạt động nhưng không có tài liệu để dựa vào.',
    noKey: 'Thêm OpenRouter API key trong Cài đặt để bắt đầu chat.',
    addKey: 'Mở cài đặt',
    reading: 'Đang đọc tài liệu',
    emptyTitle: 'Hỏi về khóa học này',
    emptyHint: 'AI trả lời dựa trên tài liệu trong thư mục đã kết nối.',
    suggestions: [
      'Tóm tắt nội dung chính của các tài liệu',
      'Khái niệm nào là quan trọng nhất?',
      'Hãy kiểm tra kiến thức của tôi về bài giảng mới nhất',
    ],
  },
  assignment: {
    title: 'Chuyển tài liệu thành nhiệm vụ',
    trigger: 'Chuyển thành nhiệm vụ (AI)',
    analyzing: 'AI đang phân tích đề bài…',
    parsed: 'AI đã tách đề bài — kiểm tra và chỉnh sửa rồi lưu.',
    save: 'Tạo nhiệm vụ',
    aiError: 'AI phân tích lỗi',
    noKey: 'Chưa có OpenRouter API key — vào Cài đặt để thêm.',
    noFolder: 'Khóa học chưa kết nối thư mục.',
    noText: 'Không trích xuất được nội dung tệp (có thể là scan/ảnh).',
    fallbackHint: 'Bạn có thể tạo nhiệm vụ thủ công ở tab Nhiệm vụ.',
  },
  taskDelete: {
    confirm: 'Xóa?',
  },
  settings: {
    title: 'Cài đặt',
    aiSection: 'Kết nối AI',
    apiKeyLabel: 'OpenRouter API key',
    apiKeyPlaceholder: 'sk-or-v1-…',
    apiKeyHint: 'Key chỉ lưu trong IndexedDB trên máy bạn — không có server trung gian.',
    modelLabel: 'Model mặc định',
    modelHint: 'Xem danh sách tại openrouter.ai/models',
    semesterLabel: 'Ngày bắt đầu học kỳ (tùy chọn)',
    test: 'Kiểm tra',
    testing: 'Đang kiểm tra…',
    keyOk: 'Key hợp lệ',
    keyInvalid: 'Key không hợp lệ',
    keyNetworkError: 'Lỗi mạng — không kiểm tra được',
    saved: 'Đã lưu',
    save: 'Lưu cài đặt',
    missingKeyBanner: 'Kết nối AI trong Cài đặt để dùng trợ lý học tập.',
    openSettings: 'Mở cài đặt',
    dataSection: 'Dữ liệu',
    backupExport: 'Xuất backup (JSON)',
    backupImport: 'Nhập backup',
    backupHint: 'Backup không chứa kết nối thư mục — hãy "Kết nối thư mục" lại cho từng khóa sau khi nạp.',
    backupSaved: 'Đã xuất file backup.',
    backupImported: 'Đã nhập backup.',
    backupError: 'File backup không hợp lệ.',
    backupExportedIcs: 'Đã xuất .ics ({n} buổi) — mở file để nhập vào Google Calendar.',
    exportIcs: 'Xuất lịch (.ics)',
  },
  importLms: {
    title: 'Nhập lịch học từ LMS',
    tabImage: 'Chụp màn hình',
    tabText: 'Dán văn bản',
    imageHint: 'Dán ảnh lịch học (Ctrl+V) hoặc chọn file — AI sẽ đọc lịch từ ảnh.',
    chooseFile: 'Chọn ảnh',
    textPlaceholder: 'Ctrl+A trang Schedule → Copy → dán vào đây…',
    analyze: 'Phân tích',
    analyzing: 'AI đang đọc lịch…',
    parseText: 'Đang phân tích văn bản…',
    noKey: 'Chưa có OpenRouter key — thêm trong Cài đặt để dùng AI, hoặc dán văn bản.',
    errorParse: 'Không trích xuất được buổi học nào.',
    tryAnother: 'Thử ảnh rõ hơn, cần thấy cả banner khoảng tuần và lưới lịch.',
    noParseText: 'Không parse được từ văn bản.',
    tryLlm: 'Dán thử nội dung đầy đủ hơn, hoặc thêm key để AI phân tích.',
    importButton: 'Nhập vào Lapis',
    done: 'Đã nhập lịch!',
    extensionTrigger: 'Hoặc: đồng bộ qua extension Lapis (mở trang LMS trước)',
  },
  gcal: {
    section: 'Google Calendar',
    clientIdLabel: 'Google OAuth Client ID',
    clientIdPlaceholder: 'xxxxx.apps.googleusercontent.com',
    clientIdHint:
      'Mặc định dùng Client ID đã cấu hình sẵn trong bản build — người dùng không cần làm gì. Chỉ điền nếu bạn tự deploy Lapis riêng.',
    syncNow: 'Đồng bộ toàn bộ lịch',
    syncWeek: 'Đồng bộ tuần này',
    syncing: 'Đang đẩy lên Google Calendar…',
    done: 'Đã tạo {n} sự kiện · bỏ qua {s} (đã có) · lỗi {f}',
    needClientId:
      'Lapis chưa được cấu hình Google Client ID (VITE_GOOGLE_CLIENT_ID) — báo cho admin, hoặc thêm thủ công ở trên.',
  },
  common: {
    save: 'Lưu',
    cancel: 'Hủy',
    edit: 'Sửa',
    remove: 'Xóa',
  },
} as const;
